version: '3.8'
services:
  database:
    image: postgres:14
    restart: always
    container_name: postgres14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ../sql/init:/docker-entrypoint-initdb.d